### ISSUE TITLE
Dica bacana

### ISSUE THREAD

**Issue by andre-lc-ferreira** [Silvana23/jogo-da-cobrinha#1]
Gostei da organização do código, seria bem legal também implementar níveis de dificuldade, por exemplo que mude a velocidade da cobrinha. 

Seria bacana também colocar as cores em variáveis, facilita depois quando precisar trocar de cor. 

```css
:root {
    --title-color: rgb(44, 139, 44);
    --background-color: rgb(34, 63, 196);
}

body {
    height: 95vh;
    width: 95;
    display: flex;
    justify-content: center;
    align-items: center;
    flex-direction: column;
    color: var(--title-color);
}

#cabecalho-principal {
    margin-bottom: 20px;
}

#pontuacao-game {
    background-color: var(--background-color);
    border-radius: 30px;
    padding: 10px;
    color: white;
    padding: 5px 50px;
    font-size: 20px;
    font-weight: 700;
    margin-left: 15px;
    display: flex;
    flex-direction: row;
    justify-content: center;
}

#pontuacao-game img {
    margin-right: 15px;
}
```

Adorei o joguinho!!!
